### ISSUE TITLE
setup error

### ISSUE THREAD

**Issue by l0pens** [boly38/drobadi#35]
Following setup
````bash
$ npm install -g drobadi
$ drobadi setup
````

I've got this issue: `ReferenceError: require is not defined in ES module scope, you can use import instead`

**Comment by boly38** [comment]
hi @l0pens , thanks for your report, I'm working on a fix 👍

**Comment by boly38** [comment]
`v1.0.1` must fix that, @l0pens please review and re-open this if needed. 🙏 👍

**Comment by boly38** [comment]
I just miss `bin/` one

**Comment by boly38** [comment]
`v1.0.2` fix that, sorry
